### PR TITLE
Debug + timer reset

### PR DESCRIPTION
**Pull request by ecoen66**
Added a reset of timer each subsequent time that the switch is turned on (if already on).
Added Debug.

### CODE REVIEW

**Comment by NorthernMan54** [comment]
@ecoen66 Ed As you seem to be really pushing the envelop with this plugin, do you want me to transfer ownership to you ?  These days I'm using node-red and HomeKit-bridged for these little hacks, and have removed this from my setup.

**Comment by ecoen66** [comment]
Haha!  Sure, I'll take it on.  Thanks for the great work that you did with it!  I wouldn't have been able to create it from scratch.

**Comment by NorthernMan54** [comment]
Am getting this error

```
ecoen66/homebridge-dummy-contact already exists
```

Can you rename your fork ?

**Comment by NorthernMan54** [comment]
Your now a maintainer on NPM

**Comment by ecoen66** [comment]
I renamed my GitHub repo.

**Comment by NorthernMan54** [comment]
Getting this error

```
ecoen66 already has a repository in the nfarina/homebridge-dummy network
```

This is because I had original forked it.  I think I need to clean that up first.

**Pull request merged**
